<a href="https://colab.research.google.com/github/Sumanasri02/data-analytics-learning-journey/blob/main/04_Python_for_Data_Analytics/02_NumPy_for_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy for Data Analytics

NumPy is the core library for numerical computing in Python.
It provides fast operations on arrays and is the foundation for Pandas and ML libraries.


In [6]:
import numpy as np
data = np.array([10, 20, 30, 40, 50])
print(data)
print(type(data))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [7]:
print("Shape:", data.shape)
print("Size:", data.size)
print("Data types:", data.dtype)

Shape: (5,)
Size: 5
Data types: int64


In [8]:
data = np.array([10, 20, 30, 40, 50])

print("First element:", data[0])
print("Last element:", data[-1])
print("Slice:", data[1:4])


First element: 10
Last element: 50
Slice: [20 30 40]


In [9]:
## Working with 2D Arrays
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)
print("Shape:", matrix.shape)


[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


## Summary

- Created NumPy arrays
- Performed mathematical operations
- Learned indexing and slicing
- Worked with 2D arrays

NumPy is the foundation of data analytics and machine learning in Python.
